# Generated by Django 4.1 on 2022-08-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_gamedata_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.game')),
                ('set', models.BooleanField(default=False)),
            ],
        ),
    ]
