# Generated by Django 4.1 on 2022-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='row1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='board',
            name='row2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
