# Generated by Django 4.1 on 2022-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_board_row1_board_row2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isComputer',
            field=models.BooleanField(default=False),
        ),
    ]
