# Generated by Django 4.1 on 2022-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_iscomputer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='isComputer',
        ),
        migrations.AddField(
            model_name='game',
            name='isSinglePlayer',
            field=models.BooleanField(default=False),
        ),
    ]
